CREATE TABLE [dbo].[HRM.Employees] (
    [PK_EmployeeID]     INT              NOT NULL,
    [EmployeeCode]      VARCHAR (32)     NOT NULL,
    [FK_CompanyID]      INT              NOT NULL,
    [FK_DepartmentID]   INT              CONSTRAINT [DF__HRM.Emplo__FK_De__6DCC4D03] DEFAULT ((-1)) NOT NULL,
    [Name]              VARCHAR (100)    NOT NULL,
    [DisplayName]       NVARCHAR (100)   NOT NULL,
    [Birthday]          DATETIME         NULL,
    [Sex]               TINYINT          NULL,
    [Address]           NVARCHAR (150)   NULL,
    [Mobile]            VARCHAR (25)     NULL,
    [PhoneNumber1]      VARCHAR (25)     NULL,
    [PhoneNumber2]      VARCHAR (25)     NULL,
    [EmployeeType]      TINYINT          CONSTRAINT [DF__HRM.Emplo__Emplo__6EC0713C] DEFAULT ((1)) NOT NULL,
    [IdentityNumber]    VARCHAR (15)     NULL,
    [DriverLicense]     VARCHAR (32)     NULL,
    [IssueLicenseDate]  DATETIME         NULL,
    [IssueLicensePlace] NVARCHAR (150)   NULL,
    [ExpireLicenseDate] DATETIME         NULL,
    [CreatedByUser]     UNIQUEIDENTIFIER NOT NULL,
    [CreatedDate]       DATETIME         CONSTRAINT [DF__HRM.Emplo__Creat__6FB49575] DEFAULT (getdate()) NOT NULL,
    [UpdatedByUser]     UNIQUEIDENTIFIER NULL,
    [UpdatedDate]       DATETIME         NULL,
    [Flags]             INT              CONSTRAINT [DF__HRM.Emplo__Flags__70A8B9AE] DEFAULT ((0)) NOT NULL,
    [IsSent]            BIT              NULL,
    [LicenseType]       INT              NULL,
    [DriverImage]       VARCHAR (MAX)    NULL,
    [IsLocked]          BIT              NOT NULL,
    [IsDeleted]         BIT              NOT NULL,
    [FK_UserID]         UNIQUEIDENTIFIER NULL,
    [DriverAvatar]      VARCHAR (MAX)    NULL,
    [LockDate]          DATETIME         NULL,
    CONSTRAINT [PK_HRM.Employees] PRIMARY KEY CLUSTERED ([PK_EmployeeID] ASC)
);

